#!/bin/bash

if [ "$#" -gt 1 ]; then
    echo "Too many parameters, correct usage '$0 <gitignore type>'"
elif [ "$#" -lt 1 ]; then
    echo "Not enough parameters, correct usage '$0 <gitignore type>'"
else
    gitignore=$(curl -s https://raw.githubusercontent.com/github/gitignore/main/$1.gitignore)
    if [ "$gitignore" == $'404: Not Found' ]; then
        echo "No .gitignore found for $1"
    else
        echo "$gitignore" > .gitignore 
        echo "Session.vim" >> .gitignore
        echo "Successfully created .gitignore"
    fi
fi
exit 0
